#pragma kernel CalculateColors


RWStructuredBuffer<float2> Velocities;
RWStructuredBuffer<float4> Colors;

const bool solidBlue;
const bool blueToRed;
const bool blueToWhite;
const float maxSpeed;

const uint numParticles;

[numthreads(64,1,1)]
void CalculateColors (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numParticles) return;

    if (solidBlue)
    {
        Colors[id.x] = float4(0.0, 0.0, 1.0, 1.0);
        return;
    }

    float intensity = saturate((abs(Velocities[id.x].x) + abs(Velocities[id.x].y)) / maxSpeed);

    if (blueToRed)
    {
        Colors[id.x] = float4(intensity, 0.0, 1 - intensity, 1.0);
        return;
    }

    if (blueToWhite)
    Colors[id.x] = float4(intensity, intensity, 1.0, 1.0);
}
