#pragma kernel CalculateColors


RWStructuredBuffer<float2> Velocities;
RWStructuredBuffer<float4> Colors;

const uint numParticles;

[numthreads(64,1,1)]
void CalculateColors (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numParticles) return;

    float intensity = saturate((abs(Velocities[id.x].x) + abs(Velocities[id.x].y)) / 40.0);
    Colors[id.x] = float4(intensity, 0.0, 1 - intensity, 1.0);
}
