#pragma kernel ExternalForces

static const int ThreadGroupSize = 256;

RWStructuredBuffer<float3> Points;
RWStructuredBuffer<float3> Velocities;

const uint numParticles;
const float gravity;
const float deltaTime;

[numthreads(ThreadGroupSize,1,1)]
void ExternalForces (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numParticles)
        return;

    Velocities[id.x] += gravity * deltaTime;
    Points[id.x].y += Velocities[id.x] * deltaTime;
}